### ISSUE TITLE
Docs and examples

### ISSUE THREAD

**Issue by mheiber** [mattkrick/redux-operations#1]
Thanks for your [Medium article](https://medium.com/@matt.krick/solving-redux-s-shortcoming-in-150-locs-540979ce6cf9#.w9hafssi5). I'm looking forward to seeing how redux-operations solves the shortcomings you describe in the article! Do you have plans to post some examples?

**Comment by bartekus** [comment]
Perhaps this will help [redux-operations-counter-example](https://github.com/mattkrick/redux-operations-counter-example)

**Comment by mheiber** [comment]
Thanks!

**Comment by mattkrick** [comment]
Here we go! https://medium.com/@matt.krick/introducing-redux-operations-332ab56e468b#.6q2pgseb8
