### ISSUE TITLE
don't touch the view layer

### ISSUE THREAD

**Issue by jedwards1211** [mattkrick/redux-operations#11]
Do I misunderstand something, or does passing a `counterReducer` into `walkState` from a view container violate separation of concerns?  That is basically the view layer dictating control logic.  The view is supposed to be a pure function of state, and have no effect on how actions get processed.

**Comment by mattkrick** [comment]
`view container` is an oxymoron. If you think of react as a MVVM, a container is the view-model (or controller if you assume it's MVC). Consider how redux handles the filtering in their todo example.  Realistically, no modern front-end framework strictly follows these, but the trend of having "smart containers" (VM) and "dumb components" (V) is close enough for all but pedagogical purposes.

To learn more, read the second to last paragraph here: https://medium.com/@matt.krick/introducing-redux-operations-332ab56e468b#.jc9etbiac

**Comment by jedwards1211** [comment]
Sure, but couldn't you at least come up with a way to avoid needing to change anything about how the view gets hooked up?

**Comment by jedwards1211** [comment]
I.e. a way that one could start using redux-operations without having to change their containers?

**Comment by jedwards1211** [comment]
I'm not trying to make a semantic argument about what to call these things, I'm just saying one should be able to change the logic that updates the state and the logic that displays the state completely independently.

**Comment by mattkrick** [comment]
I don't follow, everything inside mSTP is to retrieve state. Standard redux might include a filter, or use a memoizing function. This simply walks a state tree, no update occurs in the mSTP.

**Comment by jedwards1211** [comment]
If it just walks the state tree then what does the `counterReducer` passed in actually do?  On the surface that sounds like something that affects how state is updated.

**Comment by mattkrick** [comment]
https://github.com/mattkrick/redux-operations/blob/master/src/index.js#L42-L44

**Comment by jedwards1211** [comment]
I see
