### ISSUE TITLE
What is dynamic state?

### ISSUE THREAD

**Issue by jonathanazulay** [mattkrick/redux-operations#14]
One of the problems redux-operations is supposed to solve is _dynamic state_, but what is that? State that changes? :)

**Comment by mattkrick** [comment]
A state tree that changes, multiple reducers, etc.

**Comment by jonathanazulay** [comment]
@mattkrick Could you clarify, is this really a specific problem? It sounds like a little broad definition of a problem. State that changes is part of every application, if state wasn't dynamic (changing) we would just have a static page. I would say redux itself helps us with the problem of dynamic state.

Looking at the other points in the README it's a bit more specific:

> * Action watching (eg count how many times a particular action was run)
> * Based on itermediary results (eg 2 reducers sharing the same action & 1 needs the result of the other)
> * Async actions without thunk/promise middleware. Just write your logic directly in your reducer
> * Visual, dare I say graphiQL, API to make debugging a breeze

Just some feedback, don't get me wrong ✌️

**Comment by jonathanazulay** [comment]
@mattkrick Ok so I read the blog post. Gotcha! Basically the state tree _shape_ is dynamic.
